// export const Card_Data = [
//     {
//        id: 1,
//        name:"zoro",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 200.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//        id: 2,
//        name: "Itachi",
//        slotId: false,
//        shopId: false,
//        appStatus: null,
//        type:null,
//        appointmentStatus:"NOT-BOOKED",
//        serviceId: true,
//        amount: 250.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//        id: 3,
//        name: "Luffy",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"store",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 300.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//         id: 4,
//         name: "Sanji",
//         slotId: true,
//         shopId: true,
//         appStatus: null,
//         type:"home",
//         appointmentStatus:"BOOKED",
//         serviceId: true,
//         amount: 500.0,
//         tax1: null,
//         tax2: null,
//         gst: null,
//         cgst: null,
//         sgst: null,
//         consumerId: null,
//         createdAt: null,
//         status: null
//      },
//      {
//       id: 5,
//       name: "Thanos",
//       slotId: false,
//       shopId: false,
//       appStatus: null,
//       type:null,
//       appointmentStatus:"NOT-BOOKED",
//       serviceId: true,
//       amount: 250.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//       id: 6,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 7,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//       id: 8,
//       name: "Thanos",
//       slotId: false,
//       shopId: false,
//       appStatus: null,
//       type:null,
//       appointmentStatus:"NOT-BOOKED",
//       serviceId: true,
//       amount: 250.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//       id: 9,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 10,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//       id: 11,
//       name: "Thanos",
//       slotId: false,
//       shopId: false,
//       appStatus: null,
//       type:null,
//       appointmentStatus:"NOT-BOOKED",
//       serviceId: true,
//       amount: 250.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//       id: 12,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 13,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//       id: 14,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 15,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//       id: 16,
//       name: "Thanos",
//       slotId: false,
//       shopId: false,
//       appStatus: null,
//       type:null,
//       appointmentStatus:"NOT-BOOKED",
//       serviceId: true,
//       amount: 250.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//       id: 17,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 18,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//       id: 9,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 10,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//       id: 11,
//       name: "Thanos",
//       slotId: false,
//       shopId: false,
//       appStatus: null,
//       type:null,
//       appointmentStatus:"NOT-BOOKED",
//       serviceId: true,
//       amount: 250.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//       id: 12,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 13,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//       id: 14,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 15,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//       id: 16,
//       name: "Thanos",
//       slotId: false,
//       shopId: false,
//       appStatus: null,
//       type:null,
//       appointmentStatus:"NOT-BOOKED",
//       serviceId: true,
//       amount: 250.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//       id: 17,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 18,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//       id: 19,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 20,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
//     {
//       id: 21,
//       name: "Thanos",
//       slotId: false,
//       shopId: false,
//       appStatus: null,
//       type:null,
//       appointmentStatus:"NOT-BOOKED",
//       serviceId: true,
//       amount: 250.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//       id: 22,
//       name: "Luffy",
//       slotId: true,
//       shopId: true,
//       appStatus: null,
//       type:"store",
//       appointmentStatus:"BOOKED",
//       serviceId: true,
//       amount: 300.0,
//       tax1: null,
//       tax2: null,
//       gst: null,
//       cgst: null,
//       sgst: null,
//       consumerId: null,
//       createdAt: null,
//       status: null
//    },
//    {
//        id: 23,
//        name: "Sanji",
//        slotId: true,
//        shopId: true,
//        appStatus: null,
//        type:"home",
//        appointmentStatus:"BOOKED",
//        serviceId: true,
//        amount: 500.0,
//        tax1: null,
//        tax2: null,
//        gst: null,
//        cgst: null,
//        sgst: null,
//        consumerId: null,
//        createdAt: null,
//        status: null
//     },
// ]


